export const translations = {
  en: {
    // Navigation & Common
    home: 'Home',
    dashboard: 'Dashboard',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    signup: 'Sign Up',
    back: 'Back',
    next: 'Next',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    submit: 'Submit',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    settings: 'Settings',

    // Patient
    bookAppt: 'Book Appointment',
    myAppts: 'My Appointments',
    myRx: 'My Prescriptions',
    labReports: 'Lab Reports',
    nextSlot: 'Next: 10AM',
    downloadRx: 'Download PDF',
    viewDetails: 'View Details',
    cancelAppt: 'Cancel Appointment',
    reschedule: 'Reschedule',
    symptoms: 'Symptoms',
    vitals: 'Vitals',
    prescription: 'Prescription',
    doctor: 'Doctor',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',

    // Doctor
    patients: 'Patients',
    appointments: 'Appointments',
    myPatients: 'My Patients',
    availability: 'Availability',
    setAvailability: 'Set Availability',
    patientHistory: 'Patient History',
    writeRx: 'Write Prescription',
    viewChart: 'View Chart',
    addNotes: 'Add Notes',
    approved: 'Approved',
    pending_approval: 'Pending Approval',

    // Admin
    admins: 'Admins',
    doctors: 'Doctors',
    manage: 'Manage',
    approval: 'Approval',
    approveDr: 'Approve Doctor',
    rejectDr: 'Reject Doctor',
    statistics: 'Statistics',
    totalUsers: 'Total Users',
    totalAppts: 'Total Appointments',
    totalRx: 'Total Prescriptions',
    userManagement: 'User Management',

    // Nurse
    nurse: 'Nurse',
    nurseSchedule: 'Nurse Schedule',
    patientCare: 'Patient Care',

    // Auth
    email: 'Email',
    password: 'Password',
    phone: 'Phone Number',
    name: 'Full Name',
    role: 'Role',
    patient: 'Patient',
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',

    // Messages
    welcome: 'Welcome',
    selectRole: 'Select Your Role',
    confirmAction: 'Are you sure?',
    saved: 'Saved successfully',
    deleted: 'Deleted successfully',
    updated: 'Updated successfully',
    noData: 'No data available',
    language: 'Language',
    
    // Patient Home
    bookAppt30s: 'Reserve in 30 seconds',
    openLatestPdf: 'Open latest PDF',
    chatRx: 'Chat about medicines',
    quickActions: 'Quick actions',
    todaysAppointments: "Today's appointments",
    nomoreAppts: 'No appointments today',
    upcomingAppts: 'Upcoming appointments',
    pastAppts: 'Past appointments',
    recentRx: 'Recent prescriptions',
    
    // Doctor Dashboard
    allPatients: 'All patients',
    awaitingInterview: 'Pre-check pending',
    aiChatCompleted: 'Pre-check done',
    preCheckStage: 'Pre-check (pending + done)',
    underConsultation: 'Under consultation',
    completedToday: 'Completed today',
    approvalQueue: 'Approval queue',
    noApprovalsWaiting: 'No approvals waiting',
    publicDoctorSignups: 'Public doctor signups land here until an admin activates them.',
    approve: 'Approve',
    reject: 'Reject',
    patientQueue: 'Patient queue',
    liveQueue: 'Live queue',
    todayQueue: "Today's queue",
    
    // Admin Dashboard
    operateClinic: 'Operate the clinic from one place: approve doctors, maintain availability, and manage appointment flow.',
    pendingApprovals: 'Pending approvals',
    approvalsWaiting: 'Pending doctor approvals',
    specialty: 'Specialty',
    licenseNumber: 'License Number',
    adminConsole: 'Admin console',
    
    // Common UI
    tools: 'Tools',
    aiAssist: 'AI Assist',
    openLatest: 'Open latest',
    allAppts: 'All appointments',
    filterResults: 'Filter results',
    viewMore: 'View more',
    learnMore: 'Learn more',
    available: 'Available',
    unavailable: 'Unavailable',
    slots: 'Slots',
    patientsList: 'Patients list',
    doctorsList: 'Doctors list',
    appointmentsList: 'Appointments list',
    calendarHighlights: 'Calendar highlights',
    vitalsAtGlance: 'Vitals at a glance',
    update: 'Update',
    bp: 'BP',
    weight: 'Weight',
    recentRx: 'Recent Rx',
    viewAll: 'View All',
    appointmentBuckets: 'Appointment buckets',
    tapToJump: 'Tap once to jump into the exact stage of care.',
    inReview: 'In review',
    noApptsToday: 'No appointments today. You can still book a slot instantly.',
    noRxYet: 'No Rx yet. Try AI symptom check after your next booking.',
    queueControl: 'Queue control',
    useFilterChips: 'Use the filter chips to focus on the next patients who need your attention.',
    doctorWorkspace: 'Doctor workspace',
    token: 'Token',
    symptomChecker: 'Symptom checker',
    reviewYourQueue: 'Review only your own queue, validate APCI drafts, manage availability, and approve the final prescription from one workspace.',
    patientLogin: 'Patient login',
    doctorLogin: 'Doctor login',
    nurseLogin: 'Nurse login',
    adminLogin: 'Admin login',
    bookLiveSlots: 'Book live doctor slots in real time.',
    trackAppts: 'Track appointment status and interview handoff.',
    viewPrescriptions: 'View prescription and care updates securely.',
    afterLogin: 'After login, you can',
    premiumNursePortal: 'Premium nurse portal includes',
    credentialChecks: 'Credential-completeness checks for safer role-based access.',
    shiftWard: 'Shift, ward, and emergency handoff readiness at a glance.',
    profileFields: 'Fast link to complete required nurse profile fields.',
    trustPersonalization: 'Trust + personalization',
    doctorProfileManage: 'Manage your doctor profile details here.',
    nurseProfileManage: 'Manage nursing credentials, shift assignment, and handoff-ready contact details.',
    adminProfileManage: 'Keep the clinic admin identity and contact details current for demos and handoff.',
    phoneOrEmail: 'Phone or email',
    enterPassword: 'Enter password',
    keepSignedIn: 'Keep me signed in on this device',
    accessPortal: 'Access portal',
    accessHeader: 'Access',
    demoCredentials: 'Demo credentials',
    newAccount: 'Create a new account',
    forgotPhoneEmail: 'Can\'t find your phone or email?',
    usePhoneOrEmail: 'Use a phone number or email address. The role-specific route ensures the right workspace opens after sign-in.',
    signUp: 'Sign Up',
    passwordRequired: 'Required',
  },
  hi: {
    // Navigation & Common
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफाइल',
    logout: 'लॉग आउट',
    login: 'लॉगिन',
    signup: 'साइन अप',
    back: 'वापस',
    next: 'अगला',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    submit: 'जमा करें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    settings: 'सेटिंग्स',

    // Patient
    bookAppt: 'नियुक्ति बुक करें',
    myAppts: 'मेरी नियुक्तियां',
    myRx: 'मेरी दवाएँ',
    labReports: 'लैब रिपोर्ट',
    nextSlot: 'अगली: 10AM',
    downloadRx: 'PDF डाउनलोड करें',
    viewDetails: 'विवरण देखें',
    cancelAppt: 'नियुक्ति रद्द करें',
    reschedule: 'फिर से शेड्यूल करें',
    symptoms: 'लक्षण',
    vitals: 'महत्वपूर्ण संकेत',
    prescription: 'दवा की पर्ची',
    doctor: 'डॉक्टर',
    date: 'तारीख',
    time: 'समय',
    status: 'स्थिति',
    pending: 'पेंडिंग',
    confirmed: 'पुष्टि की गई',
    completed: 'पूर्ण',
    cancelled: 'रद्द किया गया',

    // Doctor
    patients: 'रोगी',
    appointments: 'नियुक्तियां',
    myPatients: 'मेरे रोगी',
    availability: 'उपलब्धता',
    setAvailability: 'उपलब्धता सेट करें',
    patientHistory: 'रोगी का इतिहास',
    writeRx: 'दवा की पर्ची लिखें',
    viewChart: 'चार्ट देखें',
    addNotes: 'नोट्स जोड़ें',
    approved: 'मंजूर',
    pending_approval: 'मंजूरी की प्रतीक्षा में',

    // Admin
    admins: 'व्यवस्थापक',
    doctors: 'डॉक्टर',
    manage: 'प्रबंधित करें',
    approval: 'अनुमोदन',
    approveDr: 'डॉक्टर को मंजूरी दें',
    rejectDr: 'डॉक्टर को अस्वीकार करें',
    statistics: 'आंकड़े',
    totalUsers: 'कुल उपयोगकर्ता',
    totalAppts: 'कुल नियुक्तियां',
    totalRx: 'कुल दवाएँ',
    userManagement: 'उपयोगकर्ता प्रबंधन',

    // Nurse
    nurse: 'नर्स',
    nurseSchedule: 'नर्स का शेड्यूल',
    patientCare: 'रोगी की देखभाल',

    // Auth
    email: 'ईमेल',
    password: 'पासवर्ड',
    phone: 'फोन नंबर',
    name: 'पूरा नाम',
    role: 'भूमिका',
    patient: 'रोगी',
    alreadyHaveAccount: 'पहले से खाता है?',
    createAccount: 'खाता बनाएं',
    forgotPassword: 'पासवर्ड भूल गए?',
    resetPassword: 'पासवर्ड रीसेट करें',

    // Messages
    welcome: 'स्वागत है',
    selectRole: 'अपनी भूमिका चुनें',
    confirmAction: 'क्या आप सुनिश्चित हैं?',
    saved: 'सफलतापूर्वक सहेजा गया',
    deleted: 'सफलतापूर्वक हटाया गया',
    updated: 'सफलतापूर्वक अपडेट किया गया',
    noData: 'कोई डेटा उपलब्ध नहीं है',
    language: 'Language',
    
    // Patient Home
    bookAppt30s: '30 सेकंड में बुक करें',
    openLatestPdf: 'नवीनतम PDF खोलें',
    chatRx: 'दवाओं के बारे में चैट करें',
    quickActions: 'त्वरित क्रियाएं',
    todaysAppointments: 'आज की नियुक्तियां',
    nomoreAppts: 'आज कोई नियुक्ति नहीं है',
    upcomingAppts: 'आने वाली नियुक्तियां',
    pastAppts: 'पिछली नियुक्तियां',
    recentRx: 'हाल की दवाएँ',
    
    // Doctor Dashboard
    allPatients: 'सभी रोगी',
    awaitingInterview: 'प्री-चेक लंबित',
    aiChatCompleted: 'प्री-चेक पूरा',
    preCheckStage: 'प्री-चेक (लंबित + पूरा)',
    underConsultation: 'परामर्श के अंतर्गत',
    completedToday: 'आज पूर्ण',
    approvalQueue: 'अनुमोदन कतार',
    noApprovalsWaiting: 'कोई अनुमोदन प्रतीक्षा में नहीं',
    publicDoctorSignups: 'सार्वजनिक डॉक्टर साइन-अप यहां आते हैं जब तक कोई व्यवस्थापक उन्हें सक्रिय न करे।',
    approve: 'मंजूरी दें',
    reject: 'अस्वीकार करें',
    patientQueue: 'रोगी कतार',
    liveQueue: 'लाइव कतार',
    todayQueue: 'आज की कतार',
    
    // Admin Dashboard
    operateClinic: 'एक जगह से क्लिनिक संचालित करें: डॉक्टरों को मंजूरी दें, उपलब्धता बनाए रखें, और नियुक्ति प्रवाह प्रबंधित करें।',
    pendingApprovals: 'पेंडिंग अनुमोदन',
    approvalsWaiting: 'डॉक्टर अनुमोदन की प्रतीक्षा',
    specialty: 'विशेषता',
    licenseNumber: 'लाइसेंस नंबर',
    adminConsole: 'व्यवस्थापक कंसोल',
    
    // Common UI
    tools: 'उपकरण',
    aiAssist: 'AI सहायता',
    openLatest: 'नवीनतम खोलें',
    allAppts: 'सभी नियुक्तियां',
    filterResults: 'परिणामों को फ़िल्टर करें',
    viewMore: 'अधिक देखें',
    learnMore: 'और जानें',
    available: 'उपलब्ध',
    unavailable: 'अनुपलब्ध',
    slots: 'स्लॉट',
    patientsList: 'रोगियों की सूची',
    doctorsList: 'डॉक्टरों की सूची',
    appointmentsList: 'नियुक्तियों की सूची',
    calendarHighlights: 'कैलेंडर हाइलाइट्स',
    vitalsAtGlance: 'एक नज़र में महत्वपूर्ण संकेत',
    update: 'अपडेट करें',
    bp: 'BP',
    weight: 'वजन',
    recentRx: 'हाल की दवाएँ',
    viewAll: 'सभी देखें',
    appointmentBuckets: 'नियुक्ति बकेट',
    tapToJump: 'देखभाल के सटीक चरण में जाने के लिए एक बार टैप करें।',
    inReview: 'समीक्षा में',
    noApptsToday: 'आज कोई नियुक्ति नहीं है। आप अभी भी तुरंत एक स्लॉट बुक कर सकते हैं।',
    noRxYet: 'अभी कोई दवा नहीं। अपनी अगली बुकिंग के बाद AI लक्षण जांचने का प्रयास करें।',
    queueControl: 'कतार नियंत्रण',
    useFilterChips: 'उन अगले रोगियों पर ध्यान केंद्रित करने के लिए फ़िल्टर चिप्स का उपयोग करें जिन्हें आपका ध्यान है।',
    doctorWorkspace: 'डॉक्टर कार्यक्षेत्र',
    token: 'टोकन',
    symptomChecker: 'लक्षण जांचकर्ता',
    reviewYourQueue: 'केवल अपनी कतार की समीक्षा करें, APCI ड्राफ्ट को मान्य करें, उपलब्धता प्रबंधित करें, और एक कार्यक्षेत्र से अंतिम दवा को मंजूरी दें।',
    patientLogin: 'रोगी लॉगिन',
    doctorLogin: 'डॉक्टर लॉगिन',
    nurseLogin: 'नर्स लॉगिन',
    adminLogin: 'व्यवस्थापक लॉगिन',
    bookLiveSlots: 'रीयल टाइम में लाइव डॉक्टर स्लॉट बुक करें।',
    trackAppts: 'नियुक्ति की स्थिति और साक्षात्कार हैंडऑफ को ट्रैक करें।',
    viewPrescriptions: 'दवा और देखभाल अपडेट को सुरक्षित रूप से देखें।',
    afterLogin: 'लॉगिन के बाद, आप यह कर सकते हैं',
    premiumNursePortal: 'प्रीमियम नर्स पोर्टल में शामिल है',
    credentialChecks: 'सुरक्षित भूमिका-आधारित अभिगम के लिए क्रेडेंशियल-पूर्णता जांच।',
    shiftWard: 'शिफ्ट, वार्ड, और आपातकालीन हैंडऑफ तत्परता एक नज़र में।',
    profileFields: 'आवश्यक नर्स प्रोफाइल फ़ील्ड को पूरा करने के लिए तेज़ लिंक।',
    trustPersonalization: 'विश्वास + व्यक्तिगतकरण',
    doctorProfileManage: 'अपने डॉक्टर प्रोफाइल विवरण यहां प्रबंधित करें।',
    nurseProfileManage: 'नर्सिंग क्रेडेंशियल्स, शिफ्ट असाइनमेंट, और हैंडऑफ-तैयार संपर्क विवरण प्रबंधित करें।',
    adminProfileManage: 'डेमो और हैंडऑफ के लिए क्लिनिक व्यवस्थापक पहचान और संपर्क विवरण को वर्तमान रखें।',
    phoneOrEmail: 'फोन या ईमेल',
    enterPassword: 'पासवर्ड दर्ज करें',
    keepSignedIn: 'इस डिवाइस पर मुझे साइन इन रखें',
    accessPortal: 'पोर्टल तक पहुंचें',
    accessHeader: 'प्रवेश',
    demoCredentials: 'डेमो क्रेडेंशियल्स',
    newAccount: 'नया खाता बनाएं',
    forgotPhoneEmail: 'अपनी फोन या ईमेल नहीं मिल सकते?',
    usePhoneOrEmail: 'एक फोन नंबर या ईमेल पता का उपयोग करें। भूमिका-विशिष्ट मार्ग सुनिश्चित करता है कि साइन-इन के बाद सही कार्यक्षेत्र खुल जाए।',
    signUp: 'साइन अप',
    passwordRequired: 'आवश्यक',
  }
};

export function t(key, lang = 'en') {
  return translations[lang]?.[key] || key;
}
