-- Chat context memory and realtime event stream for NIRA AI assistant
-- Supports per-user (patient/doctor) conversational continuity and queue updates.

create table if not exists public.chat_context_memory (
  id bigint generated by default as identity primary key,
  context_key text not null unique,
  user_id text,
  role text not null default 'unknown',
  language text not null default 'en',
  summary text,
  triage_level text not null default 'routine',
  escalation_band text not null default 'green',
  medications jsonb not null default '[]'::jsonb,
  allergies jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_chat_context_memory_context_key on public.chat_context_memory(context_key);

create table if not exists public.chat_events (
  id bigint generated by default as identity primary key,
  context_key text not null,
  event_type text not null,
  triage_level text,
  escalation_band text,
  queue_token integer,
  encounter_id text,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_events_context_key on public.chat_events(context_key, created_at desc);

alter table public.chat_context_memory enable row level security;
alter table public.chat_events enable row level security;

drop policy if exists "chat_context_memory_select_authenticated" on public.chat_context_memory;
create policy "chat_context_memory_select_authenticated"
  on public.chat_context_memory
  for select
  to authenticated
  using (true);

drop policy if exists "chat_events_select_authenticated" on public.chat_events;
create policy "chat_events_select_authenticated"
  on public.chat_events
  for select
  to authenticated
  using (true);
